name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.3'  # Replace with the appropriate Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate HTML
        run: python website.py build

      - name: Merge main to gh-pages
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
